### ISSUE TITLE
basket[git] fails to compile with >=libgit2-0.99

### ISSUE THREAD

**Issue by rascalDan** [basket-notepads/basket#45]
```
    14757 /var/tmp/portage/kde-misc/basket-2.49b/work/basket-2.49b/src/application.cpp: In constructor ‘Application::Application(int&,          char**)’:
    14758 /var/tmp/portage/kde-misc/basket-2.49b/work/basket-2.49b/src/application.cpp:62:13: error: ‘git_threads_init’ was not declared in          this scope; did you mean ‘git_rebase_init’?
    14759    62 |             git_threads_init();
    14760       |             ^~~~~~~~~~~~~~~~
    14761       |             git_rebase_init
    14762 /var/tmp/portage/kde-misc/basket-2.49b/work/basket-2.49b/src/application.cpp: In destructor ‘virtual Application::~Application()’:
    14763 /var/tmp/portage/kde-misc/basket-2.49b/work/basket-2.49b/src/application.cpp:73:13: error: ‘git_threads_shutdown’ was not          declared in this scope
    14764    73 |             git_threads_shutdown();
    14765       |             ^~~~~~~~~~~~~~~~~~~~
```
Found when building on Gentoo, opened related case at https://bugs.gentoo.org/710832

Looks like these functions were renamed to `git_libgit2_init` and `git_libgit2_shutdown`

**Comment by rascalDan** [comment]
Real problem is further up around version detection:
```
In file included from /usr/include/git2.h:69,
                 from /home/randomdan/dev/basket/src/application.cpp:40:
/home/randomdan/dev/basket/src/application.cpp:59:13: error: token ""0.99"" is not valid in preprocessor expressions
   59 |         #if LIBGIT2_SOVERSION >= 22
      |             ^~~~~~~~~~~~~~~~~
/home/randomdan/dev/basket/src/application.cpp:70:13: error: token ""0.99"" is not valid in preprocessor expressions
   70 |         #if LIBGIT2_SOVERSION >= 22
      |             ^~~~~~~~~~~~~~~~~
```
[fix.txt](https://github.com/basket-notepads/basket/files/4251683/fix.txt)

**Comment by blu-base** [comment]
#47 generalizes the solution of #46

**Comment by rascalDan** [comment]
Agreed.
